### PR TITLE
feat: Initial Card Sorter Program

### PR DESCRIPTION
**Pull request by FawksX**
This Pull Request Finishes the Card Shuffling and Dealing code outlined by the client listed in the brief. These include:

A basic Testing class has been implemented to test the functionality, which can be seen below:

[image](https://user-images.githubusercontent.com/30556732/223756836-cd014008-57ea-4862-b1cd-8612650aa2e1.png)

### CODE REVIEW

**Comment by Jacob-Cheadle** [comment]
Name: Jacob Cheadle (26371737)

__Fixing Logic__
Pack.cs Line 17 you have the base set as 54 cards however the jokers are not included in the pack, so this needs to be changed to 52, everything else logic wise appears to have been done very well.

__Class Commenting__
Testing.cs could benefit from comments as it is hard to understand what is going on straight away and this could assist newer developers such as myself as it took a while to realise what the similarity checker you had was doing, however the rest of the classes have been commented well and it is easy to understand their purpose.

__Code Suggestion__
Testing.cs could do with some abstraction to reduce the amount of processing used in your similarity checker, this could be fixed by just simply making a method where you input your old pack and your shuffled pack to see how similar they are rather than repeating the same code for each test of each different shuffle.

**Comment by FawksX** [comment]
@Jacob-Cheadle - Your suggestions have been implemented, if you could please re-review the PR.

**Review by Jacob-Cheadle — APPROVED** [review]

**Comment by BSpoones** [comment]
Name: Ben Soones (26511258)

**Code Suggestion**

Your Print function is very nicely implemented, however you should consider using a logger instead of Console.WriteLine as that would give more options, such as being able to format outputs. It would also allow you to categorise your logging events, for example you could easily format error messages.

**Error handling**

Your overall error handling is done very well, it is clear that a lot of testing has gone into this. However, I noticed that there is no check for list length on your sorting functions. Consider adding some error handling to ensure that there are 52 cards before shuffling, as it does not make sense to shuffle anything less than a full deck of cards

**Documentation**

Your code is very well documented, it is clear that a lot of thought has been put into commenting your code. Consider adding a readme to your repository so that anyone using this can understand exactly how to use each function and class.

**Comment by FawksX** [comment]
@BSpoones This has been completed! - Please could you re-review?

**Review by BSpoones — APPROVED** [review]

**Comment by 3ORLD** [comment]
Although you have written your Print function quite well, you might want to think about switching from Console. As WriteLine would provide more options, such the ability to format outputs, I chose it. Also, it would enable you to organise your logging activities; for instance, formatting error messages would be simple

Despite the fact that the rest of the classes have been adequately written and are simple to comprehend, Testing.cs may need some comments to help fresher developers like myself who found it difficult to grasp what the similarity checker you had was doing at first.

**Pull request merged**
